version: 2
updates:
  - package-ecosystem: 'devcontainers'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      ## Ignore all updates for 'zod' as our 'zod' version must match the
      ## version of 'zod' used by the '@modelcontextprotocol/sdk' dependency.
      - dependency-name: 'zod'
    versioning-strategy: 'increase'
  - package-ecosystem: 'npm'
    directory: '/client/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: 'zod'
    versioning-strategy: 'increase'
  - package-ecosystem: 'npm'
    directory: '/server/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: 'zod'
    versioning-strategy: 'increase'
